source /etc/X11/xinit/xinitrc
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

dunst&
thunar --daemon&
transwrap&
nm-applet&
acpi_listener&
unclutter&
/usr/libexec/geoclue-2.0/demos/agent&
redshift&

feh --no-fehbg --bg-fill $XDG_PICTURES_DIR/wallpaper

exec i3
