source /etc/X11/xinit/xinitrc
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

urxvtd&
dunst&
thunar --daemon&
transwrap&
nm-applet&
acpi_listener&
unclutter&

xrdb $XDG_CONFIG_HOME/X11/xresources
feh --no-fehbg --bg-fill $XDG_PICTURES_DIR/wallpaper

exec i3
