#!/bin/zsh

alias rss="newsboat"
alias v="vim"
alias q="exit"

alias ls="ls -hN --color=auto --group-directories-first"
alias ll="ls -l"
alias l="ll -A"
alias less="less -Q"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias bat="batcat"

alias upd="doas nala update"
alias upg="doas nala upgrade"
alias ins="doas nala install"
alias rem="doas nala purge"
alias cln="doas nala autoremove --purge"
