#!/bin/zsh

alias rss="newsboat"
alias v="vim"
alias q="exit"

alias ls="ls -hN --color=auto --group-directories-first"
alias ll="ls -l"
alias l="ll -A"
alias less="less -Q"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias bat="batcat"

alias upd="nala update"
alias upg="nala upgrade"
alias ins="nala install"
alias rem="nala purge"
alias cln="nala autoremove --purge"
