#!/bin/dash

# XDG User Directory
export XDG_DESKTOP_DIR="$HOME/"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/"
export XDG_PUBLICSHARE_DIR="$HOME/"
export XDG_DOCUMENTS_DIR="$HOME/Files"
export XDG_MUSIC_DIR="$HOME/Files/Music"
export XDG_PICTURES_DIR="$HOME/Files/Pictures"
export XDG_VIDEOS_DIR="$HOME/Files/Videos"
