#!/bin/dash

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Custom paths
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$XDG_DATA_HOME/npm/bin"
export PATH="$PATH:$HOME/Files/projects/bin"

# Default apps
export EDITOR="vi"
export BROWSER="firefox"
export PAGER="less --mouse -QR"
export BAT_PAGER="less --mouse -QRF"

# XDG Configs
export LESSHISTFILE=-
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export ZPLUG_HOME="$XDG_DATA_HOME/zplug"

# Settings
export LESS="--mouse -QR"
export COLORTERM="truecolor"
