#!/bin/dash

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Custom paths
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$XDG_DATA_HOME/npm/bin"
export PATH="$PATH:$XDG_DATA_HOME/cargo/bin"
export PATH="$PATH:$HOME/Files/projects/bin"

# Default apps
export EDITOR="vi"
export BROWSER="firefox"
export READER="zathura"
export PAGER="less --mouse -QR"
export BAT_PAGER="less --mouse -QRF"

# XDG Configs
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export LESSHISTFILE=-
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export ZPLUG_HOME="$XDG_DATA_HOME/zplug"
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# Settings
export QT_QPA_PLATFORMTHEME="qt5ct"
export LESS="--mouse -QR"
. "/home/eco/.local/share/cargo/env"
