#!/bin/zsh
HISTFILE=$XDG_CONFIG_HOME/zsh/history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_all_dups hist_ignore_space
setopt extendedglob nomatch
unsetopt autocd beep notify
bindkey -v

FPATH="$FPATH:$XDG_DATA_HOME/zfunc"
zstyle ':completion:*' menu select
#autoload -Uz compinit
#compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
#zstyle ':completion:*' use-cache on

autoload edit-command-line;
zle -N edit-command-line

function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;
        viins|main) echo -ne '\e[5 q';;
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

PS1='%B[%(!.%F{red}.%F{cyan})%n@%M%f %F{blue}%1~%f] %(!.#.$)%b '

source $ZDOTDIR/aliasrc
source $ZDOTDIR/bindrc
source $ZDOTDIR/plugrc
source $ZDOTDIR/sessionrc

source $ZDOTDIR/ngcomp

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
